### ISSUE TITLE
Can't save playlist with a / in the name off the playlist!

### ISSUE THREAD

**Issue by DaFixer83** [SegiH/Emby-and-Jellyfin-Playlist-Exporter#5]
Hi, I just trying out your program. But if there is a / in the playlist name, then it can't save the playlist.
I do think you can't nothing about it to fix this because windows don't support it.
But I just let you known.

Thankt anyway for this great program!

**Comment by SegiH** [comment]
I didn't account for a slash in the playlist name but I will fix that

**Comment by SegiH** [comment]
@DaFixer83 I just published version 2.4 in Releases. I now strip out any invalid characters from the playlist name based on characters that you are not allowed to use in Windows file names. This should fix your issue.

**Comment by DaFixer83** [comment]
Sorry for the late reply, but thanks allot!

**Comment by SegiH** [comment]
@DaFixer83 Have you tested the new version yet ? Please let me know that it works so I can close this issue.

Thanks

**Comment by DaFixer83** [comment]
Hi, I just test and it works!
Thanks allot.
But another question how to import those m3u8 files in Jellyfin?
I try to find more info about it, still no luck.

**Comment by SegiH** [comment]
You cannot import them.

The purpose of this tool is to let you back up your playlists because there's no built in way to do that.

Other media players like VLC can play m3u8 files

**Comment by SegiH** [comment]
Closing this issue since it has been resolved.
